version: '3.3'
services:
  frontend:
      build: .
      ports:
        - '3000:3000'
      volumes:
        - ./src:/usr/src/app/src
        - ./public:/usr/src/app/public
        - /usr/app/node_modules
      stdin_open: true
