version: '3.3'
services:
  mongo:
    image: 'mongo:latest'
    container_name: 'mongo'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: crypto-trading
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ~/mongo/crypto-trading-db:/data/db
    ports:
      - '27017:27017'
  frontend:
      build:
        context: ./client/
      ports:
        - '3000:3000'
      depends_on:
        - backend
      volumes:
        - ./client/src:/usr/src/app/src
        - ./client/public:/usr/src/app/public
        - /usr/app/node_modules
      stdin_open: true
  backend:
      build: .
      ports:
        - '5000:5000'
      volumes:
        - .:/usr/src/app
      env_file:
        - .env.docker
      depends_on:
        - mongo
